# Generated by Django 6.0.6 on 2026-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Applicant'), ('employer', 'Employer')], default='applicant', max_length=20),
        ),
    ]
