# Generated by Django 5.2 on 2026-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.CharField(default='2 Years', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Remote', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(default='Intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='Python, SQL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_progress_title',
            field=models.CharField(default='General Training', max_length=100),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
