# Generated by Django 6.0.6 on 2026-06-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_applicantskill_id_alter_centralizedskill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantskill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicantskill',
            name='source',
            field=models.CharField(default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='category',
            field=models.CharField(default='Local', max_length=50),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='min_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='required_certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='required_experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_fresh_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='contact_attempts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GapScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('gap_data', models.JSONField(default=list)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('job_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_logs', to='tracker.jobvacancy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_logs', to='tracker.profile')),
            ],
        ),
    ]
