# Generated by Django 5.2 on 2026-06-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tracker.jobvacancy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_jobs', to='tracker.profile')),
            ],
            options={
                'unique_together': {('profile', 'job_vacancy')},
            },
        ),
    ]
