# Generated by Django 5.2 on 2026-06-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_jobbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='tracker.jobvacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='category',
            field=models.CharField(default='jobs', max_length=50),
        ),
    ]
