# Generated by Django 5.2 on 2026-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_profile_preferred_job_alter_jobvacancy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
