# Generated by Django 5.2 on 2026-06-28 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_profile_preferred_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='slots',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='referral',
            name='accepted_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='accepted_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='bir_tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='coordination_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='decline_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='diploma_transcript',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='employer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_app_accurate_desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_app_expectations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_app_future_use',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_app_satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_app_terms_met',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_certs_genuine',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_future_referrals',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_quality',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='eval_emp_skills_accurate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='mid_probation_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='mid_probation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='mid_probation_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='pagibig_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='pre_employment_status',
            field=models.CharField(default='Incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='prev_employment_cert',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='probation_extension_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='probationary_period_months',
            field=models.PositiveIntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='reported_for_work',
            field=models.CharField(default='Awaiting', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='separation_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='sss_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='tesda_cert',
            field=models.FileField(blank=True, null=True, upload_to='pre_employment/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='work_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted — Awaiting Onboarding', 'Accepted — Awaiting Onboarding'), ('Confirmed — Onboarding', 'Confirmed — Onboarding'), ('Declined', 'Declined'), ('Hired — Probationary', 'Hired — Probationary'), ('Hired — Regular', 'Hired — Regular'), ('No Show', 'No Show'), ('Closed — No Show', 'Closed — No Show'), ('Still Employed — Performing Well', 'Still Employed — Performing Well'), ('Still Employed — On Improvement Plan', 'Still Employed — On Improvement Plan'), ('Resigned Voluntarily', 'Resigned Voluntarily'), ('Terminated by Employer', 'Terminated by Employer'), ('No Response from Employer', 'No Response from Employer'), ('No Response from Applicant', 'No Response from Applicant'), ('Regularly Employed', 'Regularly Employed'), ('Probation Extended', 'Probation Extended'), ('Separated — End of Probation', 'Separated — End of Probation'), ('Not Hired', 'Not Hired'), ('No Response', 'No Response')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
