# Generated by Django 5.2 on 2026-06-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_jobvacancy_remaining_slots_jobvacancy_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interviewing', 'Interviewing'), ('Accepted — Awaiting Onboarding', 'Accepted — Awaiting Onboarding'), ('Confirmed — Onboarding', 'Confirmed — Onboarding'), ('Declined', 'Declined'), ('Hired — Probationary', 'Hired — Probationary'), ('Hired — Regular', 'Hired — Regular'), ('No Show', 'No Show'), ('Closed — No Show', 'Closed — No Show'), ('Still Employed — Performing Well', 'Still Employed — Performing Well'), ('Still Employed — On Improvement Plan', 'Still Employed — On Improvement Plan'), ('Resigned Voluntarily', 'Resigned Voluntarily'), ('Terminated by Employer', 'Terminated by Employer'), ('No Response from Employer', 'No Response from Employer'), ('No Response from Applicant', 'No Response from Applicant'), ('Regularly Employed', 'Regularly Employed'), ('Probation Extended', 'Probation Extended'), ('Separated — End of Probation', 'Separated — End of Probation'), ('Not Hired', 'Not Hired'), ('No Response', 'No Response')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Attended', 'Attended & Completed'), ('No Show', 'No Show')], default='Enrolled', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='tracker.profile')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tracker.trainingprogram')),
            ],
            options={
                'unique_together': {('profile', 'training_program')},
            },
        ),
    ]
