# Generated by Django 5.2 on 2026-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_trainingprogram_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
