# Generated by Django 5.2 on 2026-06-28 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_jobvacancy_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='certificate_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='eligibility_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='mode',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='On-Site', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='slots',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Full', 'Full'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted')], default='Pending', max_length=20)),
                ('schedule_preference', models.CharField(choices=[('Morning', 'Morning (8am–12pm)'), ('Afternoon', 'Afternoon (1pm–5pm)'), ('Flexible', 'Flexible')], default='Flexible', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to='tracker.profile')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.trainingprogram')),
            ],
            options={
                'unique_together': {('profile', 'training_program')},
            },
        ),
    ]
