# Generated by Django 5.2 on 2026-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_trainingprogram_certificate_offered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='certificate_offered',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='eligibility_notes',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='remaining_slots',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='slots',
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='TrainingApplication',
        ),
    ]
