# Generated by Django 5.2 on 2026-06-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_trainingprogram_certificate_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='applicant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to='tracker.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('general', 'General'), ('match_alert', 'Match Alert'), ('offer_sent', 'Offer Sent'), ('offer_response', 'Offer Response')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tracker.jobvacancy'),
        ),
    ]
