# Generated by Django 5.2 on 2026-07-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_notification_rich_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applicant_documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.profile')),
            ],
        ),
    ]
