# Generated by Django 5.2 on 2026-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
