# Generated by Django 6.0.6 on 2026-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_trainingprogram_skills_addressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='location',
            field=models.CharField(blank=True, default='PESO Training Center', max_length=255, null=True),
        ),
    ]
