# Generated by Django 6.0.6 on 2026-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_trainingprogram_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='slots',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
